package com.mybatisMe.Dao;

import com.mybatisMe.entities.Customers;
import com.mybatisMe.entities.CustomersExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CustomersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Wed Feb 26 12:02:21 CST 2020
     */
    int countByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Wed Feb 26 12:02:21 CST 2020
     */
    int deleteByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Wed Feb 26 12:02:21 CST 2020
     */
    int deleteByPrimaryKey(Integer customernumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Wed Feb 26 12:02:21 CST 2020
     */
    int insert(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Wed Feb 26 12:02:21 CST 2020
     */
    int insertSelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Wed Feb 26 12:02:21 CST 2020
     */
    List<Customers> selectByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Wed Feb 26 12:02:21 CST 2020
     */
    Customers selectByPrimaryKey(Integer customernumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Wed Feb 26 12:02:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") Customers record, @Param("example") CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Wed Feb 26 12:02:21 CST 2020
     */
    int updateByExample(@Param("record") Customers record, @Param("example") CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Wed Feb 26 12:02:21 CST 2020
     */
    int updateByPrimaryKeySelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Wed Feb 26 12:02:21 CST 2020
     */
    int updateByPrimaryKey(Customers record);
}